### ISSUE TITLE
i really need help

### ISSUE THREAD

**Issue by khengyun** [Temanor/Custom-ComfyGray#1]
sorry for texting your issue

but I saw you comment a video on this repo. I have 1 question. How to have a brave interface like you. I couldn't find anything similar to that interface.

https://github.com/wong2/chatgpt-google-extension/issues/161#issuecomment-1370014372

**Comment by Temanor** [comment]
I haven't customised my brave search engine in an way so I'm guessing you are talking about the browser.
I am using Firefox with custom css but using the brave search engine, because it looks good and is privacy focused.
Treestyle tabs for tabs on the left side and nightTab for empty tabs.
